# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ca.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63\x61.proto\"!\n\tPublicKey\x12\t\n\x01n\x18\x01 \x01(\t\x12\t\n\x01\x64\x18\x02 \x01(\t\"u\n\x0b\x43\x65rtificate\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\t\x12\t\n\x01\x65\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08\x64uration\x18\x05 \x01(\x03\x12\x0c\n\x04\x63\x61Id\x18\x06 \x01(\t\x12\x11\n\tsignature\x18\x07 \x01(\t\"9\n\x0fRegisterRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\t\x12\t\n\x01\x65\x18\x03 \x01(\t\"&\n\x12\x43\x65rtificateRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"C\n\x1e\x43\x65rtificateVerificationRequest\x12!\n\x0b\x63\x65rtificate\x18\x01 \x01(\x0b\x32\x0c.Certificate\"2\n\x1f\x43\x65rtificateVerificationResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\"$\n\x10PublicKeyRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x10\x45ncryptedMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0f\x41\x63knowledgement\x12\x10\n\x08response\x18\x01 \x01(\t2\x94\x02\n\x1b\x43\x65rtificateAuthorityService\x12/\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12\x37\n\x12RequestCertificate\x12\x13.CertificateRequest\x1a\x0c.Certificate\x12\x33\n\x12RequestCAPublicKey\x12\x11.PublicKeyRequest\x1a\n.PublicKey\x12V\n\x11VerifyCertificate\x12\x1f.CertificateVerificationRequest\x1a .CertificateVerificationResponse2Z\n\x16MessageExchangeService\x12@\n\x17ReceiveEncryptedMessage\x12\x11.EncryptedMessage\x1a\x10.Acknowledgement\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ca_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PUBLICKEY']._serialized_start=12
  _globals['_PUBLICKEY']._serialized_end=45
  _globals['_CERTIFICATE']._serialized_start=47
  _globals['_CERTIFICATE']._serialized_end=164
  _globals['_REGISTERREQUEST']._serialized_start=166
  _globals['_REGISTERREQUEST']._serialized_end=223
  _globals['_CERTIFICATEREQUEST']._serialized_start=225
  _globals['_CERTIFICATEREQUEST']._serialized_end=263
  _globals['_CERTIFICATEVERIFICATIONREQUEST']._serialized_start=265
  _globals['_CERTIFICATEVERIFICATIONREQUEST']._serialized_end=332
  _globals['_CERTIFICATEVERIFICATIONRESPONSE']._serialized_start=334
  _globals['_CERTIFICATEVERIFICATIONRESPONSE']._serialized_end=384
  _globals['_PUBLICKEYREQUEST']._serialized_start=386
  _globals['_PUBLICKEYREQUEST']._serialized_end=422
  _globals['_REGISTERRESPONSE']._serialized_start=424
  _globals['_REGISTERRESPONSE']._serialized_end=459
  _globals['_ENCRYPTEDMESSAGE']._serialized_start=461
  _globals['_ENCRYPTEDMESSAGE']._serialized_end=496
  _globals['_ACKNOWLEDGEMENT']._serialized_start=498
  _globals['_ACKNOWLEDGEMENT']._serialized_end=533
  _globals['_CERTIFICATEAUTHORITYSERVICE']._serialized_start=536
  _globals['_CERTIFICATEAUTHORITYSERVICE']._serialized_end=812
  _globals['_MESSAGEEXCHANGESERVICE']._serialized_start=814
  _globals['_MESSAGEEXCHANGESERVICE']._serialized_end=904
# @@protoc_insertion_point(module_scope)
