# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timestamp_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17timestamp_service.proto\"+\n\x0f\x44ocumentRequest\x12\x18\n\x10\x64ocument_content\x18\x01 \x01(\t\"8\n\x10\x44ocumentResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\'\n\x11PublicKeyResponse\x12\x12\n\npublic_key\x18\x01 \x01(\t2J\n\x10TimestampService\x12\x36\n\rStampDocument\x12\x10.DocumentRequest\x1a\x11.DocumentResponse\"\x00\x32\x46\n\x10PublicKeyService\x12\x32\n\x12GetServerPublicKey\x12\x06.Empty\x1a\x12.PublicKeyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timestamp_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOCUMENTREQUEST']._serialized_start=27
  _globals['_DOCUMENTREQUEST']._serialized_end=70
  _globals['_DOCUMENTRESPONSE']._serialized_start=72
  _globals['_DOCUMENTRESPONSE']._serialized_end=128
  _globals['_EMPTY']._serialized_start=130
  _globals['_EMPTY']._serialized_end=137
  _globals['_PUBLICKEYRESPONSE']._serialized_start=139
  _globals['_PUBLICKEYRESPONSE']._serialized_end=178
  _globals['_TIMESTAMPSERVICE']._serialized_start=180
  _globals['_TIMESTAMPSERVICE']._serialized_end=254
  _globals['_PUBLICKEYSERVICE']._serialized_start=256
  _globals['_PUBLICKEYSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
